Add new release and promote workflow
canonical/charm-openstack-service-checks pull request #166
Opened 2024-05-03 13:03 UTC by rgildein

Using official actions directly.

2024-05-06 14:04 UTC, aieri requested changes

2024-05-06 14:04 UTC, aieri commented on .github/workflows/release.yaml
> +          sudo lxd init --auto
needs to be updated to use the setup-lxd action

2024-05-06 16:41 UTC, gabrielcocenza approved these changes

2024-05-06 18:02 UTC, zxhdaze approved these changes

2024-05-06 20:06 UTC, aieri approved these changes

2024-05-07 02:27 UTC, jneo8 approved these changes

2024-05-07 16:21 UTC, merged